export interface IAdbCommand {
  name: string
  command: string
  category: 'Batería' | 'Sistema' | 'Red' | 'Debug'
  description: string
  tags?: string[]
}

export const ADB_COMMANDS: IAdbCommand[] = [
  // =================== BATERÍA ===================
  {
    name: 'Estado de batería',
    command: 'dumpsys battery',
    category: 'Batería',
    description: 'Muestra nivel, voltaje, temperatura, estado de carga y tecnología.',
    tags: ['nivel', 'temperatura', 'carga', 'voltaje'],
  },
  {
    name: 'Resetear simulación de batería',
    command: 'dumpsys battery reset',
    category: 'Batería',
    description: 'Restaura los valores reales de la batería tras pruebas de simulación.',
    tags: ['reset', 'limpiar'],
  },
  {
    name: 'Simular nivel de batería',
    command: 'dumpsys battery set level 100',
    category: 'Batería',
    description: 'Fuerza el nivel de batería al valor especificado (0-100%).',
    tags: ['level', 'simular'],
  },
  {
    name: 'Simular desconexión del cargador',
    command: 'dumpsys battery unplug',
    category: 'Batería',
    description: 'Simula que el dispositivo funciona con batería sin cargador.',
    tags: ['desconectar', 'unplug'],
  },
  {
    name: 'Simular carga AC (corriente)',
    command: 'dumpsys battery set ac 1',
    category: 'Batería',
    description: 'Simula que el dispositivo está conectado a un cargador de pared.',
    tags: ['cargar', 'ac', 'wall'],
  },
  {
    name: 'Simular carga USB',
    command: 'dumpsys battery set usb 1',
    category: 'Batería',
    description: 'Simula que el dispositivo está conectado a un puerto USB de PC.',
    tags: ['usb', 'carga'],
  },
  {
    name: 'Estadísticas históricas de batería',
    command: 'dumpsys batterystats',
    category: 'Batería',
    description: 'Estadísticas completas de consumo energético por app y hardware.',
    tags: ['stats', 'consumo', 'historial'],
  },
  {
    name: 'Resetear estadísticas de batería',
    command: 'dumpsys batterystats --reset',
    category: 'Batería',
    description: 'Reinicia el contador de estadísticas de batería (ideal tras calibración).',
    tags: ['reset', 'calibrar'],
  },

  // =================== SISTEMA ===================
  {
    name: 'Reiniciar dispositivo',
    command: 'reboot',
    category: 'Sistema',
    description: 'Reinicia el sistema operativo Android de inmediato.',
    tags: ['reiniciar', 'restart'],
  },
  {
    name: 'Reiniciar en Recovery',
    command: 'reboot recovery',
    category: 'Sistema',
    description: 'Reinicia el dispositivo en el menú de recuperación / wipe.',
    tags: ['recovery', 'wipe', 'twrp'],
  },
  {
    name: 'Reiniciar en Bootloader / Fastboot',
    command: 'reboot bootloader',
    category: 'Sistema',
    description: 'Reinicia el dispositivo en el modo bootloader / fastboot.',
    tags: ['bootloader', 'fastboot', 'flash'],
  },
  {
    name: 'Ver todas las propiedades del sistema',
    command: 'getprop',
    category: 'Sistema',
    description: 'Lista todas las propiedades y configuración de build del sistema.',
    tags: ['propiedades', 'props', 'build'],
  },
  {
    name: 'Consumo de memoria RAM',
    command: 'dumpsys meminfo',
    category: 'Sistema',
    description: 'Muestra el uso detallado de memoria RAM global y por proceso.',
    tags: ['ram', 'memoria', 'free'],
  },
  {
    name: 'Espacio de almacenamiento (df)',
    command: 'df -h',
    category: 'Sistema',
    description: 'Espacio libre y utilizado en todas las particiones montadas.',
    tags: ['disco', 'almacenamiento', 'espacio'],
  },
  {
    name: 'Tiempo de actividad (Uptime)',
    command: 'uptime',
    category: 'Sistema',
    description: 'Tiempo que lleva el sistema encendido y carga media de CPU.',
    tags: ['tiempo', 'uptime', 'carga'],
  },
  {
    name: 'Resolución de pantalla actual',
    command: 'wm size',
    category: 'Sistema',
    description: 'Muestra la resolución física y la resolución configurada.',
    tags: ['pantalla', 'resolucion', 'width', 'height'],
  },
  {
    name: 'Densidad DPI de pantalla',
    command: 'wm density',
    category: 'Sistema',
    description: 'Muestra la densidad de píxeles (DPI) actual de la pantalla.',
    tags: ['dpi', 'densidad', 'escala'],
  },
  {
    name: 'Recortar caché de aplicaciones',
    command: 'pm trim-caches 999999999999',
    category: 'Sistema',
    description: 'Obliga al sistema a liberar la memoria caché de todas las apps.',
    tags: ['cache', 'limpieza', 'trim'],
  },
  {
    name: 'Simular tecla Home',
    command: 'input keyevent 3',
    category: 'Sistema',
    description: 'Envía el evento de botón Home para volver a la pantalla principal.',
    tags: ['home', 'tecla', 'boton'],
  },
  {
    name: 'Simular tecla Atrás',
    command: 'input keyevent 4',
    category: 'Sistema',
    description: 'Envía el evento de botón Atrás (Back).',
    tags: ['back', 'atras'],
  },
  {
    name: 'Simular botón de encendido (Power)',
    command: 'input keyevent 26',
    category: 'Sistema',
    description: 'Bloquea o desbloquea la pantalla pulsando Power.',
    tags: ['power', 'bloquear', 'pantalla'],
  },

  // =================== RED ===================
  {
    name: 'Configuración de red e IP (ifconfig)',
    command: 'ifconfig',
    category: 'Red',
    description: 'Muestra interfaces de red activas, MACs e IPs asignadas.',
    tags: ['ip', 'interfaces', 'mac'],
  },
  {
    name: 'Direcciones IP detalladas (ip addr)',
    command: 'ip addr show',
    category: 'Red',
    description: 'Muestra todas las interfaces IPv4 e IPv6 configuradas.',
    tags: ['ip', 'ipv4', 'ipv6'],
  },
  {
    name: 'Puertos y conexiones activas (netstat)',
    command: 'netstat -tuln',
    category: 'Red',
    description: 'Lista los puertos TCP/UDP abiertos y sockets en escucha.',
    tags: ['puertos', 'sockets', 'listen'],
  },
  {
    name: 'Estado de Wi-Fi detallado',
    command: 'dumpsys wifi',
    category: 'Red',
    description: 'Muestra información detallada del adaptador y enlace Wi-Fi.',
    tags: ['wifi', 'wlan', 'ssid', 'rssi'],
  },
  {
    name: 'Probar conectividad a Internet (Ping)',
    command: 'ping -c 4 8.8.8.8',
    category: 'Red',
    description: 'Envía 4 paquetes ICMP al servidor DNS de Google para verificar conexión.',
    tags: ['ping', 'conexion', 'dns', 'internet'],
  },
  {
    name: 'Encender Wi-Fi',
    command: 'svc wifi enable',
    category: 'Red',
    description: 'Activa la antena Wi-Fi del dispositivo.',
    tags: ['wifi', 'on', 'activar'],
  },
  {
    name: 'Apagar Wi-Fi',
    command: 'svc wifi disable',
    category: 'Red',
    description: 'Desactiva la antena Wi-Fi del dispositivo.',
    tags: ['wifi', 'off', 'desactivar'],
  },
  {
    name: 'Activar datos móviles',
    command: 'svc data enable',
    category: 'Red',
    description: 'Habilita la conexión de datos celulares móviles.',
    tags: ['datos', '4g', '5g', 'movil'],
  },
  {
    name: 'Desactivar datos móviles',
    command: 'svc data disable',
    category: 'Red',
    description: 'Deshabilita la conexión de datos celulares móviles.',
    tags: ['datos', 'apagar', 'desconectar'],
  },
  {
    name: 'Estadísticas de consumo de datos',
    command: 'dumpsys netstats detail',
    category: 'Red',
    description: 'Muestra el tráfico de datos descargado y subido por cada UID/App.',
    tags: ['consumo', 'bytes', 'red'],
  },

  // =================== DEBUG ===================
  {
    name: 'App en primer plano (Top Activity)',
    command: 'dumpsys activity top | grep ACTIVITY',
    category: 'Debug',
    description: 'Detecta qué paquete y actividad está visualizándose en pantalla.',
    tags: ['top', 'focus', 'actividad', 'app'],
  },
  {
    name: 'Listar apps instaladas de terceros',
    command: 'pm list packages -3',
    category: 'Debug',
    description: 'Lista los nombres de paquete de todas las apps instaladas por el usuario.',
    tags: ['apps', 'paquetes', 'terceros'],
  },
  {
    name: 'Listar apps del sistema',
    command: 'pm list packages -s',
    category: 'Debug',
    description: 'Lista los paquetes de aplicaciones preinstaladas del sistema.',
    tags: ['sistema', 'apps', 'system'],
  },
  {
    name: 'Listar apps deshabilitadas',
    command: 'pm list packages -d',
    category: 'Debug',
    description: 'Muestra qué aplicaciones se encuentran congeladas o deshabilitadas.',
    tags: ['deshabilitadas', 'disabled', 'congeladas'],
  },
  {
    name: 'Capturar pantalla a /sdcard',
    command: 'screencap -p /sdcard/screenshot.png',
    category: 'Debug',
    description: 'Guarda una captura de pantalla actual en el almacenamiento interno.',
    tags: ['captura', 'screenshot', 'imagen'],
  },
  {
    name: 'Procesos en ejecución (ps)',
    command: 'ps -ef',
    category: 'Debug',
    description: 'Muestra todos los procesos activos con UID, PID y nombre de binario.',
    tags: ['procesos', 'ps', 'pid'],
  },
  {
    name: 'Monitoreo de CPU en tiempo real (top)',
    command: 'top -m 10 -n 1',
    category: 'Debug',
    description: 'Muestra los 10 procesos con mayor porcentaje de uso de CPU.',
    tags: ['top', 'cpu', 'rendimiento'],
  },
  {
    name: 'Últimos 100 logs de Logcat',
    command: 'logcat -d -v time | tail -100',
    category: 'Debug',
    description: 'Vuelca los últimos 100 mensajes del registro del sistema.',
    tags: ['logcat', 'logs', 'errores'],
  },
  {
    name: 'Limpiar buffer de Logcat',
    command: 'logcat -c',
    category: 'Debug',
    description: 'Vacía la memoria intermedia de logs del sistema.',
    tags: ['limpiar', 'clear', 'logcat'],
  },
  {
    name: 'Auditoría de políticas SELinux',
    command: 'getenforce',
    category: 'Debug',
    description: 'Comprueba si el kernel está en modo Enforcing o Permissive.',
    tags: ['selinux', 'seguridad', 'enforce'],
  },
]
